apiVersion: v1
kind: ServiceAccount
metadata:
  name: bay-sa
  namespace: shipyard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bay-role
  namespace: shipyard
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bay-role-binding
  namespace: shipyard
subjects:
  - kind: ServiceAccount
    name: bay-sa
    namespace: shipyard
roleRef:
  kind: Role
  name: bay-role
  apiGroup: rbac.authorization.k8s.io
